language: node_js
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
# End submodules fix
node_js:
  - '10'
# Make sure setup runs before test stage
# Test stage is implicitly defined and makes use of matrix expansion
stages:
  - setup
  - test
  - report
script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - if [ "$DEMOS" == "TRUE" ]; then npm run-script test-demo -- \*; else npm run coverage -- "$TEST_NAME" "$TEST_SUITE"; fi
  - kill %1
  - ls -la
  - ls -la .nyc_output

jobs:
  include:
    - stage: setup
      script: mkdir .nyc_output && touch .nyc_output/file
      workspaces:
        create:
          name: coverage
          paths:
            - .nyc_output
    - stage: test
      name: 1
      env: DEMOS="TRUE"
      workspaces:
        create:
          name: 1
          paths:
            - .nyc_output
    - name: 2
      env: TEST_NAME='base' TEST_SUITE=''
      workspaces:
        create:
          name: 2
          paths:
            - .nyc_output
    - name: 3
      env: TEST_NAME='bigNumber' TEST_SUITE=''
      workspaces:
        create:
          name: 3
          paths:
            - .nyc_output
    - name: 4
      env: TEST_NAME='negativeNumber' TEST_SUITE=''
      workspaces:
        create:
          name: 4
          paths:
            - .nyc_output
    - name: 5
      env: TEST_NAME='bigNumber-negativeNumber' TEST_SUITE=''
      workspaces:
        create:
          name: 5
          paths:
            - .nyc_output
    - name: 6
      env: TEST_NAME='restAPI' TEST_SUITE=''
      workspaces:
        create:
          name: 6
          paths:
            - .nyc_output
    - name: 7
      env: TEST_NAME='bits' TEST_SUITE=''
      workspaces:
        create:
          name: 7
          paths:
            - .nyc_output
    - name: 8
      env: TEST_NAME='fixedpoint' TEST_SUITE='share'
      workspaces:
        create:
          name: 8
          paths:
            - .nyc_output
    - name: 9
      env: TEST_NAME='fixedpoint' TEST_SUITE='arithmetic'
      workspaces:
        create:
          name: 9
          paths:
            - .nyc_output
    - name: 10
      env: TEST_NAME='fixedpoint' TEST_SUITE='constant arithmetic'
      workspaces:
        create:
          name: 10
          paths:
            - .nyc_output
    - name: 11
      env: TEST_NAME='fixedpoint' TEST_SUITE='constant comparison'
      workspaces:
        create:
          name: 11
          paths:
            - .nyc_output
    - name: 12
      env: TEST_NAME='fixedpoint' TEST_SUITE='comparison'
      workspaces:
        create:
          name: 12
          paths:
            - .nyc_output
    - name: 13
      env: TEST_NAME='fixedpoint' TEST_SUITE='ifelse'
      workspaces:
        create:
          name: 13
          paths:
            - .nyc_output
    - name: 14
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='share'
      workspaces:
        create:
          name: 14
          paths:
            - .nyc_output
    - name: 15
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='arithmetic'
      workspaces:
        create:
          name: 15
          paths:
            - .nyc_output
    - name: 16
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='constant arithmetic'
      workspaces:
        create:
          name: 16
          paths:
            - .nyc_output
    - name: 17
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='constant comparison'
      workspaces:
        create:
          name: 17
          paths:
            - .nyc_output
    - name: 18
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='comparison'
      workspaces:
        create:
          name: 18
          paths:
            - .nyc_output
    - name: 19
      env: TEST_NAME='fixedpoint-negativeNumber' TEST_SUITE='ifelse'
      workspaces:
        create:
          name: 19
          paths:
            - .nyc_output
    - stage: report
      script:
        - ls -la
        - ls -la .nyc_output
        - npm run coverage:report
      workspaces:
        use:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19

notifications:
  slack:
    secure: DuaE/q/B/la8rNGXsn/p3owtWZmn6th1rAJUXTIUUU48OjE86ehzMD40JMLMyAty3f/NHYOPufS7//AfpaIf4cGE6/4wHcTVoLOzRv6aP7WM0SvMy1WS5QgP7ryIjciyXFczknQ+JSMcXlxQDKtMCT7wBIwQO1WrB+T8e617y575t/ofO39k9Za1NA81MlrdWxTIWTDGMo17T+Pd/zz4ImHGYoifUzXi9DdH/4Zgy9SJxWQJ3PO/5RWef4qu1mBGXdanIEd63mYjIIQh8nJLn3pvWp7rQnChmwRqURDc6hpwdPJqeWO5knqhNlu/u7/TJI985rvTOPYljXfReXdF1OEHuq+prWGhv4VbxJzTpQ9PJZ42Ac1k6nCaMCJfCphpsUL48+qgeRY9IyBoqARw4Ne8hTerc7P0T/iQxgZk8zVVahdf0C27sPD0B563gMWvFKxW41YbvHwku7CpReaCt+pcGTd77p+v0mGZGlWNv/kV6KXMBHmQXGYEdVSpscEdlFbByZKagY8lrsadyZtaAaUCdD4VRGaYCWPh/+eBsVdS94r7XRHXBceiSd3ZY093r7lMO9yGnyDwqSydL7JgncO/GxWMhsEz2vRV+bgZlLU2yo60H8Kg1jvmpVP3o0d8wfkDUyLVOkJiSDZ+LuhQZ10f1MnP3AtVrMJFEKITmqw=
